spring:
  application:
    name: msproducts
  datasource:
    url: jdbc:postgresql://db:5432/db_product
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080