spring:
  application:
    name: eurekaserver
  security:
    user:
      name: cursoms-eureka-user
      password: ecok-usr-eeuramssur

server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false