services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway
    hostname: gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true